apiVersion: v1
kind: ConfigMap
metadata:
  name:  "cfg-api"
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  appsettings.json: |-
    {
      "DatabaseSettings": {
        "ConnectionString": {{ required "A valid .Values.env.config.ConnectionString entry required!" .Values.env.config.ConnectionString | quote }},
        "DatabaseName": "ProductDb",
        "CollectionName": "Products"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }