{{- $name := include "web.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-web"
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ShoppingAPIUrl: http://api:8000/