apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-api
  namespace: ecomm
  labels:
    app: stress-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-api
  template:
    metadata:
      name: stress-api
      labels:
        app: stress-api
      annotations: {
        "sidecar.istio.io/inject": "false"
      }
    spec:
      containers:
        - name: stress-api
          image: alpine:3.12
          command:
          - /bin/sh
          - -c
          - "while true; do wget -q -O- http://shoppingapi-service:8000/product; done"